name: CI/CD Pipeline com Alerta

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodar Testes
        run: echo "Executando testes..."

      - name: Construir Imagem Docker
        run: docker build -t minha-app .

      # CONFIGURAÇÃO DO ALERTA DISCORD (Semana 6)
      - name: Enviar Alerta ao Discord
        uses: sarisia/actions-status-discord@v1
        if: always() # Rodar sempre, mesmo se der erro acima
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }} # Nome da Secret que você criou
          status: ${{ job.status }}
          content: "Opa! O pipeline do @${{ github.actor }} terminou."
          title: "Status do Workflow"
