name: CI/CD Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  # Isso é o CI (Integração Contínua)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Construir Imagem Docker
        run: docker build -t minha-app-docker:latest .

  # Isso é o CD (Entrega Contínua)
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Isso aqui faz a linha conectando as duas caixas!
    steps:
      - name: Simulando deploy
        run: echo "Deploy da imagem Docker realizado com sucesso 🚀"
